### ISSUE TITLE
TODO before launch

### ISSUE THREAD

**Issue by jobin212** [jobin212/rc-place#15]
- [ ] Big, draggable board
- [ ] Timelapse (See https://community.fly.io/t/how-to-copy-files-off-a-vm/1651/6)
- [ ] Ensure thread safety (mutex)
- [x] Bot creation session, examples (multiple languages)
- [x] GET /tile -- get color, last updated, last updater of single tile (nice to have)
- [ ] BONUS MSPaint features
- [ ] BONUS Give web client a message/timer/API until they can place again -- e.g. you have 0.4 s until you can update
